### PR TITLE
fix(server): use friendly error message for statistic computation

### LINKED ISSUE #248: "Lighthouse Error" after extending dashboard view to >=100 builds
At least that's what i'm seeing sometimes on the lhci canary instance.

https://lhci-canary.herokuapp.com/app/projects/ffb1f9c0-465f-4dc5-9407-1ed7e06ac7c4/dashboard?runUrl=http%3A%2F%2Flocalhost%3APORT%2Fapp%2Fprojects%2Flighthouse-viewer

What I saw:

1. I tried MAX and got an error
1. I tried 100 and got an error
1. I tried 50 and it worked
1. I tried 100 again and it worked.
1. I tried MAX again and it worked.

Soooooooo it fails intermittently. 🤷‍♂ 

Since it works now I can't get a screenshot. Sorry.

### PR DESCRIPTION
**Pull request by patrickhulce**
closes #248

### CODE REVIEW

File: packages/server/src/ui/components/async-loader.jsx [hunk 1]
```diff
@@ -23,14 +23,14 @@ const Resource404 = () => {
...
+ * @param {{loadingState: LoadingState, asyncData: T | undefined, render: (data: T) => JSX.Element, renderLoading?: () => JSX.Element, renderError?: () => JSX.Element}} props */
 export const AsyncLoader = props => {
-  const {asyncData, loadingState, render, renderLoading} = props;
+  const {asyncData, loadingState, render, renderLoading, renderError} = props;
 
   if (loadingState === 'loaded') {
     return asyncData === undefined ? <Resource404 /> : render(asyncData);
   } else if (loadingState === 'error') {
-    return <h1>Lighthouse Error</h1>;
+    return renderError ? renderError() : <h1>Lighthouse Error</h1>;
```
Comment (paulirish) [inline packages/server/src/ui/components/async-loader.jsx]: is it more accurate to say "Lighthouse CI Server Error" instead of "Lighthouse Error" ?  if so, i'd love to, just to help people understand .

File: packages/server/src/ui/routes/project-dashboard-redesign/category-card.jsx [hunk 2]
```diff
@@ -372,6 +372,13 @@ export const CategoryCard = props => {
           loadingState={props.loadingState}
           asyncData={props.statistics}
           renderLoading={() => <span>Loading, please wait...</span>}
+          renderError={() => (
+            <span style={{textAlign: 'center'}}>
+              Woah, looks like there&apos;s a lot of data here!
+              <br />
+              Statistics are being computed now. Please try again in a few minutes.
```
Comment (paulirish) [inline packages/server/src/ui/routes/project-dashboard-redesign/category-card.jsx]: 👍

File: packages/server/src/ui/components/async-loader.jsx (hunk 1 above)
Comment (patrickhulce) [reply packages/server/src/ui/components/async-loader.jsx]: good call 👍 
```suggestion
    return renderError ? renderError() : <h1>Lighthouse CI Server Error</h1>;
```
